<div class="login-body">
    <article class="container-login center-block">
        <section>
            <ul id="top-bar" class="nav nav-tabs nav-justified">
                <li class="active"><a href="#login-access">Login</a></li>
            </ul>
            <div class="tab-content tabs-login col-lg-12 col-md-12 col-sm-12 cols-xs-12">
                <div id="login-access">
                    <h2><i class="md-verified-user"></i> E-Thesis</h2>

                    <form method="post" accept-charset="utf-8" autocomplete="off" role="form" novalidate=""
                          action="<?= $actionLogin ?>"
                          class="form-horizontal" id="form-login">
                        <div class="form-group">
                            <input type="text" class="form-control" name="login" id="inputLogin"
                                   required=""
                                   placeholder="Username" tabindex="1" value=""/>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" id="inputPassword"
                                   required=""
                                   placeholder="Password" value="" tabindex="2"/>
                        </div>

                        <p class="text-danger" id="login-alert" style="display: none"></p>

                        <br/>

                        <div class="form-group">
                            <button type="submit" name="log-me-in" id="submit" tabindex="3"
                                    class="btn btn-lg btn-primary">Login
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </article>
</div>

<script>
    $(document).ready(function () {
        $("#form-login").submit(function (e) {
            e.preventDefault();
            $("#login-alert").hide();
            var login = $(this).serialize();
            var form = this;
            $(this).hide();
            $('#login-access').append('<div class="text-center" id="loading"><i class="md md-sync md-5x md-spin-reverse"></i></div>');

            setTimeout(function () {
                $("#loading").remove();
                $("#login-alert").show().html('ชื่อหรือรหัสผ่านไม่ถูกต้อง').delay(5000).fadeOut(500);
                $(form).show();

            }, 2000);

            //console.log(login);
        });
    });

</script>


<style>
    /*@import url("http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700");*/

    login-body {
        /*font-family: Open Sans;*/
        font-size: 14px;
        line-height: 1.42857;
        background: #333333;
        height: 350px;
        padding: 0;
        margin: 0;
    }

    .container-login {
        min-height: 0;
        width: 480px;
        color: #333333;
        margin-top: 40px;
        padding: 0;
    }

    .center-block {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    .container-login > section {
        margin-left: 0;
        margin-right: 0;
        padding-bottom: 10px;
    }

    #top-bar {
        display: inherit;
    }

    .nav-tabs.nav-justified {
        border-bottom: 0 none;
        width: 100%;
    }

    .nav-tabs.nav-justified > li {
        display: table-cell;
        width: 1%;
        float: none;
    }

    .container-login .nav-tabs.nav-justified > li > a,
    .container-login .nav-tabs.nav-justified > li > a:hover,
    .container-login .nav-tabs.nav-justified > li > a:focus {
        background: #ea533f;
        border: medium none;
        color: #ffffff;
        margin-bottom: 0;
        margin-right: 0;
        border-radius: 0;
    }

    .container-login .nav-tabs.nav-justified > .active > a,
    .container-login .nav-tabs.nav-justified > .active > a:hover,
    .container-login .nav-tabs.nav-justified > .active > a:focus {
        background: #ffffff;
        color: #333333;
    }

    .container-login .nav-tabs.nav-justified > li > a:hover,
    .container-login .nav-tabs.nav-justified > li > a:focus {
        background: #de2f18;
    }

    .tabs-login {
        background: #ffffff;
        border: medium none;
        margin-top: -1px;
        padding: 10px 30px;
    }

    .container-login h2 {
        color: #ea533f;
    }

    .form-control {
        background-color: #ffffff;
        background-image: none;
        border: 1px solid #999999;
        border-radius: 0;
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
        color: #333333;
        display: block;
        font-size: 14px;
        height: 34px;
        line-height: 1.42857;
        padding: 6px 12px;
        transition: border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
        width: 100%;
    }

    .container-login .checkbox {
        margin-top: -15px;
    }

    .container-login button {
        background-color: #ea533f;
        border-color: #e73e28;
        color: #ffffff;
        border-radius: 0;
        font-size: 18px;
        line-height: 1.33;
        padding: 10px 16px;
        width: 100%;
    }

    .container-login button:hover,
    .container-login button:focus {
        background: #de2f18;
        border-color: #be2815;
    }
</style>