<select class="form-control" id="TEST_SELECT2">
    <option value="select2/select2" selected="selected">select2/select2</option>
</select>

<script>
    $("#TEST_SELECT2").select2({
        ajax: {
            url: "https://api.github.com/search/repositories",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page
                };
            },
            processResults: function (data, page) {
                // parse the results into the format expected by Select2.
                // since we are using custom formatting functions we do not need to
                // alter the remote JSON data
                return {
                    results: data.items
                };
            },
            cache: true
        },
        minimumInputLength: 2
    });
</script>