<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 18/2/2558
 * Time: 10:30
 */

define('AUTH_FALSE_J', '"auth":false');


#log Process
define('LOG_LOGIN', 'MSG_LOGIN');
define('LOG_OPEN_PAGE', 'MSG_OPEN_PAGE');

define('LOG_ADD_COMPLETE', 'MSG_ADD_COMPLETE');
define('LOG_UPDATE_COMPLETE', 'MSG_UPDATE_COMPLETE');
define('LOG_DELETE_COMPLETE', 'MSG_DELETE_COMPLETE');

define('LOG_ADD_ERROR', 'MSG_ADD_ERROR');
define('LOG_UPDATE_ERROR', 'MSG_UPDATE_ERROR');
define('LOG_DELETE_USED', 'MSG_DELETE_USED');

define('LOG_CANCEL_COMPLETE', 'MSG_CANCEL_COMPLETE');

define('LOG_IMPORT_COMPLETE', 'MSG_IMPORT_COMPLETE');
define('LOG_IMPORT_DUPLICATE', 'MSG_IMPORT_DUPLICATE');
define('LOG_IMPORT_ERROR', 'MSG_IMPORT_ERROR');
define('LOG_IMPORT_ITEM_ERROR', 'MSG_IMPORT_ITEM_ERROR');





