<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 17/3/2558
 * Time: 10:24
 */

$table_name = 'groupuser_' . rand(0, 999999);
?>
<br/><br/>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <?= $formclass->get_inputgroup_complate($table_name, false) ?>
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-12">
        <table id="<?= $table_name ?>" class="display cell-border hover" cellspacing="0" width="100%"></table>
        <script>
            $.material.init();
            var O<?=$table_name?> = $('#<?=$table_name?>').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: '<?=$burl. 'getdata';?>',
                        type: 'POST'
                    },
                    language: (lang == 'th' ? {
                        "sProcessing": "กำลังดำเนินการ...",
                        "sLengthMenu": "แสดง_MENU_ แถว",
                        "sZeroRecords": "ไม่พบข้อมูล",
                        "sInfo": "แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว",
                        "sInfoEmpty": "แสดง 0 ถึง 0 จาก 0 แถว",
                        "sInfoFiltered": "(กรองข้อมูล _MAX_ ทุกแถว)",
                        "sInfoPostFix": "",
                        "sSearch": "ค้นหา:",
                        "sUrl": "",
                        "oPaginate": {
                            "sFirst": "เริ่มต้น",
                            "sPrevious": "ก่อนหน้า",
                            "sNext": "ถัดไป",
                            "sLast": "สุดท้าย"
                        }
                    } : ''),
                    dom: '<"#top">rt<"#bottom"ilp>',
                    columns: [
                        {
                            name: 'pk_id',
                            data: 'pk_id',
                            orderable: false,
                            visible: false
                        },
                        {
                            name: 'GRP_TOPMENU',
                            data: 'GRP_TOPMENU',
                            class: 'dt-center',
                            width: '10%',
                            orderable: true,
                            title: '<?=$Lang->label('GRP_TOPMENU')?>'
                        },
                        {
                            name: 'GRP_NAME_TH',
                            data: 'GRP_NAME_TH',
                            class: 'dt-head-center',
                            width: '30%',
                            orderable: true,
                            title: '<?=$Lang->label('GRP_NAME_TH')?>'
                        },
                        {
                            name: 'GRP_NAME_EN',
                            data: 'GRP_NAME_EN',
                            class: 'dt-head-center',
                            width: '30%',
                            orderable: true,
                            title: '<?=$Lang->label('GRP_NAME_EN')?>'
                        },
                        {
                            name: 'GRP_USER_TYPE',
                            data: 'GRP_USER_TYPE',
                            class: 'dt-head-center',
                            orderable: true,
                            title: '<?=$Lang->label('GRP_USER_TYPE')?>'
                        },
                    ]
                })
                    .on('init.dt', function () {
                        $('#<?=$table_name?>_wrapper #top').html('')
                            .append('<button type="button" id="ADD" class="btn btn-sm btn-primary"><i class="md-add"></i> <?=$Lang->label('ADD')?></button>')
                            .append('<button type="button" id="EDIT" class="btn btn-sm btn-warning disabled"><i class="md-edit"></i> <?=$Lang->label('EDIT')?></button>')
                            .append('<button type="button" id="DELETE" class="btn btn-sm btn-danger disabled"><i class="md-remove"></i> <?=$Lang->label('DELETE')?></button>');
                        $('#<?=$table_name?>_wrapper #top').children().click(function () {
                            var ID = 'main_tab';
                            var manage = $(this).attr('id');
                            var la = $(this).html();
                            var murl = '';
                            if (manage == 'DELETE') {
                                murl = '<?=$burl?>setdata/' + manage;
                            } else {
                                murl = '<?=$burl?>getform/' + manage;
                            }
                            jQuery.ajax({
                                type: "POST",
                                url: murl,
                                data: 'tablename=<?=$table_name?>&pk_id=' + (O<?=$table_name?>.row('.selected').length > 0 ? O<?=$table_name?>.row('.selected').data().pk_id : '' ),
                                success: function (result) {
                                    if (manage == 'ADD' || manage == 'EDIT') {
                                        if (manage == 'EDIT') {
                                            //Set Label Tab
                                            la += ' [' + O<?=$table_name?>.row('.selected').data().GRP_NAME_TH + ']';
                                        }
                                        var elm = add_tab(ID);
                                        elm.tab.html(la);
                                        elm.content.html(result);
                                    } else if (manage == 'DELETE') {
                                        var res = decode_json(result);
//                                        clog(res);
                                        if (res.msg) {
                                            alert(res.msg);
                                        } else {
                                            alert('ผิดพลาด!');
                                        }
                                        $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').addClass('disabled');
                                        O<?=$table_name?>.ajax.reload();
                                    }
                                }
                            });
                        });
                    })
                ;
            $('#<?=$table_name?> tbody').on('click', 'tr', function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                    $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').addClass('disabled');
                } else {
                    O<?=$table_name?>.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                    $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').removeClass('disabled');
                }
            });

        </script>
    </div>
</div>
