<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 17/3/2558
 * Time: 10:24
 */

$table_name = 'log_' . rand(0, 999999);
?>
<br/><br/>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <form id="<?= $formname ?>" class="form-horizontal" onsubmit="return false">
            <div class="row">
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">
                            <?= $labelgroup['LOG_USER'] ?>
                            <?= $input['LOG_USER'] ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">
                            <?= $labelgroup['LOG_PAGE'] ?>
                            <?= $input['LOG_PAGE'] ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">
                            <?= $labelgroup['LOG_PROCESS'] ?>
                            <?= $input['LOG_PROCESS'] ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">
                            <?= $labelgroup['LOG_DATE'] ?>
                            <?= $input['LOG_DATE'] ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">
                            <?= $labelgroup['LOG_BROWSER_INFO'] ?>
                            <?= $input['LOG_BROWSER_INFO'] ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-6">
                    <div class="form-group">
                        <div class="input-group">

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-offset-5">
                    <button type="button" class="btn btn-primary btn-raised"
                            onclick="O<?= $table_name ?>.search(JSON.stringify($('#<?= $formname ?>').serializeArray())).draw();">
                        <i class="md-search"></i> <?= $Lang->label('SEARCH') ?></button>
                    <button type="reset" class="btn btn-default btn-raised">
                        <i class="md-refresh"></i> <?= $Lang->label('CLEAR') ?></button>
                </div>
            </div>
        </form>

    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-12">
        <table id="<?= $table_name ?>" class="display cell-border hover" cellspacing="0" width="100%"></table>
        <script>
            $.material.init();
            var O<?=$table_name?> = $('#<?=$table_name?>').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '<?=$di->url->get('system/logs/getdata');?>',
                    type: 'POST'
                },
                language: (lang == 'th' ? {
                    "sProcessing": "กำลังดำเนินการ...",
                    "sLengthMenu": "แสดง_MENU_ แถว",
                    "sZeroRecords": "ไม่พบข้อมูล",
                    "sInfo": "แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว",
                    "sInfoEmpty": "แสดง 0 ถึง 0 จาก 0 แถว",
                    "sInfoFiltered": "(กรองข้อมูล _MAX_ ทุกแถว)",
                    "sInfoPostFix": "",
                    "sSearch": "ค้นหา:",
                    "sUrl": "",
                    "oPaginate": {"sFirst": "เิริ่มต้น", "sPrevious": "ก่อนหน้า", "sNext": "ถัดไป", "sLast": "สุดท้าย"}
                } : ''),
                dom: '<"#top">rt<"#bottom"ilp>',
                columns: decode_json('<?php
                /*
                  'name' => '',
                    'data' => [],
                    'className' => null,
                    'searchable' => false,
                    'orderable' => true,
                    'width' => null,
                    'visible' => true,
                    'title' => ''
                 */

                    echo json_encode([
                    ['name' => 'LOG_ID','data' => 'LOG_ID','orderable' => false, 'visible'=>false],
                    ['name' => 'LOG_USER','data' => 'LOG_USER','orderable' => true,'title' => $Lang->label('LOG_USER')],
                    ['name' => 'LOG_PAGE','data' => 'LOG_PAGE','orderable' => true,'title' => $Lang->label('LOG_PAGE')],
                    ['name' => 'LOG_PROCESS','data' => 'LOG_PROCESS','orderable' => true,'title' => $Lang->label('LOG_PROCESS')],
                    ['name' => 'LOG_DATE','data' =>  'LOG_DATE','orderable' => true,'title' => $Lang->label('LOG_DATE')],
                    ['name' => 'LOG_IP','data' => 'LOG_IP','orderable' => true,'title' => $Lang->label('LOG_IP')],
                    ['name' => 'LOG_BROWSER_INFO','data' => 'LOG_BROWSER_INFO','orderable' => false,'title' => $Lang->label('LOG_BROWSER_INFO')],
                    ]);
                ?>')
            });


        </script>
    </div>
</div>
