<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 17/3/2558
 * Time: 10:24
 */

$table_name = 'module_' . rand(0, 999999);
?>
<br/><br/>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <?= $formclass->get_inputgroup_complate($table_name, false) ?>
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-12">
        <table id="<?= $table_name ?>" class="display cell-border hover" cellspacing="0" width="100%"></table>
        <script>
            $.material.init();
            <?=$valid?>

            var O<?=$table_name?> = $('#<?=$table_name?>').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: '<?=$burl.'getdata';?>',
                        type: 'POST'
                    },
                    language: (lang == 'th' ? {
                        "sProcessing": "กำลังดำเนินการ...",
                        "sLengthMenu": "แสดง_MENU_ แถว",
                        "sZeroRecords": "ไม่พบข้อมูล",
                        "sInfo": "แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว",
                        "sInfoEmpty": "แสดง 0 ถึง 0 จาก 0 แถว",
                        "sInfoFiltered": "(กรองข้อมูล _MAX_ ทุกแถว)",
                        "sInfoPostFix": "",
                        "sSearch": "ค้นหา:",
                        "sUrl": "",
                        "oPaginate": {
                            "sFirst": "เิริ่มต้น",
                            "sPrevious": "ก่อนหน้า",
                            "sNext": "ถัดไป",
                            "sLast": "สุดท้าย"
                        }
                    } : ''),
                    dom: '<"#top">rt<"#bottom"ilp>',
                    columns: decode_json('<?php

                    echo json_encode([
                    ['name' => 'pk_id','data' => 'pk_id','orderable' => false, 'visible'=>false],
                    ['name' => 'MOD_CODE','data' => 'MOD_CODE','orderable' => true,'title' => 'รหัสโหนด'],
                    ['name' => 'MOD_PARENT_ID','data' => 'MOD_PARENT_ID','orderable' => true,'title' => $Lang->label('MOD_PARENT_ID')],
                    ['name' => 'MOD_ORDER','data' => 'MOD_ORDER','orderable' => true,'title' => $Lang->label('MOD_ORDER')],
                    ['name' => 'MOD_NAME_TH','data' => 'MOD_NAME_TH','orderable' => true,'title' => $Lang->label('MOD_NAME_TH')],
                    ['name' => 'MOD_NAME_EN','data' =>  'MOD_NAME_EN','orderable' => true,'title' => $Lang->label('MOD_NAME_EN')],
                    ['name' => 'MOD_URL','data' => 'MOD_URL','orderable' => true,'title' => $Lang->label('MOD_URL')],
//                    ['name' => 'MANAGE','data' => 'MANAGE','orderable' => false,'title' => $Lang->label('MANAGE')],
                    ]);
                ?>')
                }).on('init.dt', function () {
                    $('#<?=$table_name?>_wrapper #top').html('')
                        .append('<button type="button" id="ADD" class="btn btn-sm btn-primary"><i class="md-add"></i> <?=$Lang->label('ADD')?></button>')
                        .append('<button type="button" id="EDIT" class="btn btn-sm btn-warning disabled"><i class="md-edit"></i> <?=$Lang->label('EDIT')?></button>')
                        .append('<button type="button" id="DELETE" class="btn btn-sm btn-danger disabled"><i class="md-remove"></i> <?=$Lang->label('DELETE')?></button>');
                    $('#<?=$table_name?>_wrapper #top').children().click(function () {
                        var ID = 'main_tab';
                        var manage = $(this).attr('id');
                        var la = $(this).html();
                        var murl = '';
                        if (manage == 'DELETE') {
                            murl = '<?=$burl?>setdata/' + manage;
                        } else {
                            murl = '<?=$burl?>getform/' + manage;
                        }
                        jQuery.ajax({
                            type: "POST",
                            url: murl,
                            data: 'tablename=<?=$table_name?>&pk_id=' + (O<?=$table_name?>.row('.selected').length > 0 ? O<?=$table_name?>.row('.selected').data().pk_id : '' ),
                            success: function (result) {
                                if (manage == 'ADD' || manage == 'EDIT') {
                                    if (manage == 'EDIT') {
                                        //Set Label Tab
                                        la += ' [' + O<?=$table_name?>.row('.selected').data().MOD_NAME_TH + ']';
                                    }
                                    var elm = add_tab(ID);
                                    elm.tab.html(la);
                                    elm.content.html(result);
                                } else if (manage == 'DELETE') {
                                    var res = decode_json(result);
//                                        clog(res);
                                    if (res.msg) {
                                        alert(res.msg);
                                    } else {
                                        alert('ผิดพลาด!');
                                    }
                                    $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').addClass('disabled');
                                    O<?=$table_name?>.ajax.reload();
                                }
                            }
                        });
                    });
                })
                ;

            $('#<?=$table_name?> tbody').on('click', 'tr', function () {
                if ($(this).hasClass('selected')) {
                    $(this).removeClass('selected');
                    $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').addClass('disabled');
                } else {
                    O<?=$table_name?>.$('tr.selected').removeClass('selected');
                    $(this).addClass('selected');
                    $('#<?=$table_name?>_wrapper #top #EDIT').add('#<?=$table_name?>_wrapper #top #DELETE').removeClass('disabled');
                }
            });


        </script>
    </div>
</div>
