<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?php
    \Phalcon\Tag::appendTitle(' - E-Thesis');
    echo \Phalcon\Tag::getTitle();
    $import_script = [
        'css' => [
            'public/resource/css/bootstrap.min.css',
            'public/resource/css/material-design-iconic-font.min.css',
            'public/resource/css/ripples.min.css',
            'public/resource/css/material.min.css',
            'public/resource/plugin/datetimepicker/css/bootstrap-datetimepicker.min.css',
            //'public/resource/plugin/chosen/chosen.min.css',
            'public/resource/plugin/select2/css/select2.css',
            'public/resource/plugin/formvalidation/css/formValidation.min.css',
            'public/resource/plugin/DataTables/media/css/jquery.dataTables.min.css',
            'public/resource/plugin/DataTables/media/css/jquery.dataTables_themeroller.css',
            'public/resource/style.css',
        ],
        'js' => [
            'public/resource/js/jquery-2.1.3.min.js',
            //'public/resource/js/angular.min.js',
            'public/resource/js/bootstrap.min.js',
            'public/resource/js/ripples.min.js',
            'public/resource/js/material.min.js',
            'public/resource/plugin/datetimepicker/js/bootstrap-datetimepicker.min.js',
//            'public/resource/plugin/validator.min.js',
            'public/resource/plugin/formvalidation/js/formValidation.min.js',
            'public/resource/plugin/formvalidation/js/framework/bootstrap.min.js',

            //'public/resource/plugin/chosen/chosen.jquery.min.js',
            //'public/resource/plugin/chosen/chosen.proto.min.js',
            'public/resource/plugin/select2/js/select2.min.js',
            'public/resource/plugin/select2/js/i18n/th.js',
            'public/resource/plugin/datetimepicker/js/locales/bootstrap-datetimepicker.th.js',
            'public/resource/plugin/formvalidation/js/language/th_TH.js',
            'public/resource/plugin/DataTables/media/js/jquery.dataTables.min.js',
//            'public/resource/plugin/DataTables/media/js/jquery.dataTables.Bootstrap3.js',
            'public/resource/app.js',
        ]
    ];
    foreach ($import_script as $type => $arr_file) {
        foreach ($arr_file as $file) {
            if ($type == 'css') {
                echo \Phalcon\Tag::stylesheetLink($file);
            } else if ($type == 'js') {
                echo \Phalcon\Tag::javascriptInclude($file);
            }
        }
    }
    //echo \Phalcon\Tag::javascriptInclude('public/resource/core.js');
    ?>
    <style>
        .navbar {
            margin: 20;
        }
    </style>
</head>
<body>

<?= $this->getContent() ?>



<script>
    $.material.init();
    $('[data-toggle="tooltip"]').tooltip();
    <?php
        $session = $_SESSION[\EThesis\Library\Session::SESSION_NAME .'lang'];
    ?>
    var lang = '<?=$session?>';

</script>
</body>
</html>

