<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <?php
    \Phalcon\Tag::appendTitle(' - E-Thesis');
    echo \Phalcon\Tag::getTitle();
    $import_script = [
        'css' => [
            'public/resource/css/bootstrap.min.css',
            'public/resource/css/material-design-iconic-font.min.css',
            'public/resource/css/ripples.min.css',
            'public/resource/css/material.min.css',
//            'public/resource/plugin/datetimepicker/css/bootstrap-datetimepicker.min.css',
            'public/resource/plugin/datepicker/datepicker.css',


            //'public/resource/plugin/chosen/chosen.min.css',
            'public/resource/plugin/select2/css/select2.css',
            'public/resource/plugin/formvalidation/css/formValidation.min.css',
            'public/resource/plugin/DataTables/media/css/jquery.dataTables.min.css',
            'public/resource/plugin/DataTables/media/css/jquery.dataTables_themeroller.css',
            'public/resource/style.css',
        ],
        'js' => [
            'public/resource/js/jquery-2.1.3.min.js',
            //'public/resource/js/angular.min.js',
            'public/resource/js/bootstrap.min.js',
            'public/resource/js/ripples.min.js',
            'public/resource/js/material.min.js',
//            'public/resource/plugin/datetimepicker/js/bootstrap-datetimepicker.js',
//            'public/resource/plugin/datetimepicker/js/locales/bootstrap-datetimepicker.th.js',

            'public/resource/plugin/datepicker/bootstrap-datepicker.min.js',
            'public/resource/plugin/datepicker/bootstrap-datepicker-thai.min.js',
            'public/resource/plugin/datepicker/locales/bootstrap-datepicker.th.js',

//            'public/resource/plugin/validator.min.js',
            'public/resource/plugin/formvalidation/js/formValidation.min.js',
            'public/resource/plugin/formvalidation/js/framework/bootstrap.min.js',

            //'public/resource/plugin/chosen/chosen.jquery.min.js',
            //'public/resource/plugin/chosen/chosen.proto.min.js',
            'public/resource/plugin/select2/js/select2.full.min.js',
            'public/resource/plugin/select2/js/i18n/th.js',
            'public/resource/plugin/formvalidation/js/language/th_TH.js',
            'public/resource/plugin/DataTables/media/js/jquery.dataTables.min.js',
//            'public/resource/plugin/DataTables/media/js/jquery.dataTables.Bootstrap3.js',
            'public/resource/app.js',
        ]
    ];
    foreach ($import_script as $type => $arr_file) {
        foreach ($arr_file as $file) {
            if ($type == 'css') {
                echo \Phalcon\Tag::stylesheetLink($file);
            } else if ($type == 'js') {
                echo \Phalcon\Tag::javascriptInclude($file);
            }
        }
    }
    //echo \Phalcon\Tag::javascriptInclude('public/resource/core.js');
    ?>
    <style>
        .navbar {
            margin: 20;
        }
    </style>
</head>
<body>
<?php
$lang = $di->session->get('lang');
$base_url = $di->url->get();
?>
<script>
    var lang = '<?=$lang?>';
    var base_url = '<?=$base_url?>';
</script>

<?= $this->getContent() ?>



<script>
    $.material.init();
    $('[data-toggle="tooltip"]').tooltip();



    function access_group(id, title) {
        var form = '#form-login';
        $(form).hide();
        $('#login-access').append('<div class="text-center" id="loading"><i class="md md-sync md-5x md-spin-reverse"></i></div>');
        $("#login-alert").html('');
        $.ajax({
            dataType: 'json',
            method: 'POST',
            url: base_url + 'main/auth/logingroup',
            data: 'grouploginid=' + id,
            success: function (result) {
                if (result.error !== false || typeof result.msg !== 'undefined') {
                    $("#login-alert").show().html(result.msg).delay(5000).fadeOut(500);
                    $("#loading").remove();
                } else {
                    window.location = result.reurl;
                    $("#loading").remove();
                }
            },
            error: function () {
                $("#loading").remove();
                $("#login-alert").show().html('ไม่สามารถเชื่อมต่อเซิฟเวอร์ได้').delay(5000).fadeOut(500);
            }
        });
    }

    function logout() {
        var form = '#form-login';
        $.ajax({
            dataType: 'json',
            method: 'POST',
            url: base_url + 'main/auth/logout',
            success: function (result) {
                $("#loading").remove();
                window.location = base_url;
            },
            error: function () {
                $("#loading").remove();
                $("#login-alert").show().html('ไม่สามารถเชื่อมต่อเซิฟเวอร์ได้').delay(5000).fadeOut(500);
            }
        });
    }

</script>
</body>
</html>

