<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 20/1/2558
 * Time: 13:01
 */
?>
<div class="navbar" style="margin-bottom: 0px;
  background: -webkit-linear-gradient(90deg, #2a0845 10%, #6441A5 90%); /* Chrome 10+, Saf5.1+ */
  background:    -moz-linear-gradient(90deg, #2a0845 10%, #6441A5 90%); /* FF3.6+ */
  background:     -ms-linear-gradient(90deg, #2a0845 10%, #6441A5 90%); /* IE10 */
  background:      -o-linear-gradient(90deg, #2a0845 10%, #6441A5 90%); /* Opera 11.10+ */
  background:         linear-gradient(90deg, #2a0845 10%, #6441A5 90%); /* W3C */

">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?= '/e-thesis' ?>">E-Thesis</a>
    </div>

</div>



<div class="container">
    <?= $this->getContent() ?>
</div>
<style>
    .navber-small {
        min-height: 10px;
    }

    .navber-small .navbar-nav > li > a {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
        border-radius: 0;
        border: 2px inset rgba(0, 255, 233, 0.52) !important;
        /*border-right: 2px inset #b5c8b4 !important;*/
        background-color: #005d4f !important;
    }

</style>




