<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 20/1/2558
 * Time: 13:01
 */
?>
<div class="navbar navbar-material-deep-purple-700" style="margin-bottom: 0px">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<?= '/e-thesis' ?>">E-Thesis</a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">เข้าใช้งาน <b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0)">Attapon.th</a></li>
                    <li><a href="javascript:void(0)">Another action</a></li>
                    <li><a href="javascript:void(0)">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:void(0)">Separated link</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>


<div class="navbar navbar-material-purple-400 navber-small">
    <div class="navbar-collapse collapse navbar-inverse-collapse">
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">ระบบ <b
                        class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="javascript:void(0)">Attapon.th</a></li>
                    <li><a href="javascript:void(0)">Another action</a></li>
                    <li><a href="javascript:void(0)">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:void(0)">Separated link</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="container">
    <?= $this->getContent() ?>
</div>
<style>
    .navber-small {
        min-height: 10px;
    }

    .navber-small .navbar-nav > li > a {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
        border-radius: 0;
        border: 2px inset rgba(0, 255, 233, 0.52) !important;
        /*border-right: 2px inset #b5c8b4 !important;*/
        background-color: #005d4f !important;
    }

</style>




