<?php
/**
 * Created by PhpStorm.
 * User: attapon.th
 * Date: 20/1/2558
 * Time: 13:01
 */
?>

<?php
$menu_class = new \EThesis\Library\MenuEThesis();
$html = $menu_class->createMenu();

if ($di->session->get('auth') === true && is_numeric($di->session->get('grouplogin'))) {


    ?>


    <div class="navbar navbar-material-deep-purple-700" style="margin-bottom: 0px">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $di->url->get('') ?>">E-Thesis</a>
        </div>
        <div class="navbar-collapse collapse navbar-inverse-collapse">

        </div>
    </div>
    <script>
        $(function () {
            $('a[href="#"]').on('click', function (e) {
                e.preventDefault();
            });
        });
    </script>


    <div class="navbar navbar-material-purple-400 navber-small">
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
                <?= $html ?>
            </ul>
        </div>
    </div>


    <style>
        .navber-small {
            min-height: 10px;
        }

        .navber-small .navbar-nav > li > a {
            padding-top: 5px;
            padding-bottom: 5px;
        }

        .nav-tabs > li.active > a, .nav-tabs > li.active > a:hover, .nav-tabs > li.active > a:focus {
            color: inherit;
            background-color: rgba(255, 255, 255, .2) !important;
        }

        span.input-group-addon {
            font-weight: 600;
            color: #0c0c0c;
        }

        .form-horizontal .checkbox {
            padding-top: 0px;
        }

        .radio label {
            padding-left: 30px;
        }

        .checkbox label {
            padding-left: 10px;

        }

        .checkbox label span {
            padding-right: 5px;
        }

    </style>

    <div class="col-md-12" id="main_tab">
    </div>

    <script>

        setInterval(function () {
            $.ajax({
                type: "POST",
                url: "<?= $di->url->get('main/auth/get_checklogin/'.$di->session->get('key'));?>",
                dataType: 'json',
                success: function (result) {
                    if (result.auth !== true) {
                        alert('หมดเวลาการเข้าใช้งานระบบ (Session Time Out!!!)');
                        window.location = '<?=$di->url->get()?>';
                    }
                },
                error: function () {
                    alert('หมดเวลาการเข้าใช้งานระบบ (Session Time Out!!!)');
                    window.location = '<?=$di->url->get()?>';
                }
            });

        }, (10 * 60 * 1000));

        function count_tab(ID) {
            var count = jQuery("#" + ID + " > ul > li").length;
            return count;
        }
        function add_tab(ID) {
            var elm = $('#' + ID);
            if (count_tab(ID) < 1) {
                var ck = elm.html('<ul class="nav nav-tabs"></ul> <div id="' + ID + '_content" class="tab-content"> </div>');
            }
            var num_tab = Math.floor(Math.random() * 99999);

            var tab_link = elm.children('ul').first();
            tab_link.append('<li class=""><a href="#' + ID + '_link-' + num_tab + '"  data-toggle="tab"><i class="md md-sync md-lg md-spin-reverse"></i></a></li>');

            var tab_content = elm.children('#' + ID + '_content').first();
            tab_content.append('<div class="tab-pane fade" id="' + ID + '_link-' + num_tab + '">'
            + '<button type="button" style="margin:1px" class="close btn btn-danger btn-raised" onclick="javascript:close_tab(\'' + ID + '\',' + num_tab + ')"><i class="md-close"></i></button>'
            + '<div class="well">'
            + '<div data-number="' + num_tab + '" id="' + ID + '_content"><div class="text-center"> <i class="md md-sync md-5x md-spin-reverse"></i> </div></div>'
            + '</div>'
            + '</div>');
            tab_link.children().last().children().first().click();
            return {
                tab: tab_link.children().last().children().first(),
                content: $('#' + ID + '_content[data-number="' + num_tab + '"]'),
                num_tab: num_tab
            }
        }

        function close_active(ID) {
            var id = $("#" + ID + " ul li[class=active]").children('a').first().attr('href');
            var sp = id.split('-');
            var num_tab = sp[1];
            close_tab(ID, num_tab);
        }

        function close_tab(ID, num_tab) {
            var elm = $('#' + ID);
            if (count_tab(ID) < 2) {
                elm.html('');
                return true;
            } else {
                $('a[href="#' + ID + '_link-' + num_tab + '"]').parent().first().remove();
                $('#' + ID + '_link-' + num_tab + '').remove();
                elm.children('ul').first().children().last().children().first().click();
                return true;
            }
            return false;
        }

        function close_alltab(ID) {
            var elm = $('#' + ID);
            elm.html('');
        }


        function call_page(label, url, data) {
            var ID = 'main_tab';
            close_alltab(ID);
            var elm = add_tab(ID);
            jQuery.ajax({
                type: "POST",
                url: "<?= $di->url->get('');?>" + url,
                data: 'permision=' + data,
                success: function (result) {
                    if (result == '') {
                        alert('หมดเวลาการใช้งานระบบ หรือคุณไม่ได้รับสิทธิ์ในการเข้าถึง');
                    } else if (result == 'false') {
                        alert('หมดเวลาการใช้งานระบบ');
                    } else {
                        elm.tab.html(label);
                        elm.content.html(result);
                    }
                },
                error: function () {
                    close_alltab(ID);
                    alert('!ผิดพลาด 404 ไม่เจอหน้านี้');
                }
            });
        }


        window.onbeforeunload = function (e) {
            e = e || window.event;
            if (count_tab('main_tab') > 0) {
                if (e) {
                    e.returnValue = 'คุณแน่ใจว่าต้องการออกจากหน้านี้?';
                }
                return 'คุณแน่ใจว่าต้องการออกจากหน้านี้?';
            }

        };

        function clog(print) {
            console.log(print);
        }
    </script>


    <style>

        .navbar .navber-center {
            text-align: center;
        }
    </style>
    <div class="navbar navbar-fixed-bottom navbar-material-deep-purple-700 navber-small" style="margin-bottom: 0px">
        <div class="navbar-collapse navber-center collapse navbar-inverse-collapse">
            <ul class="nav navbar-nav" style=" display: inline-block;float: none;">
                <li class="dropdown">
                    <?php
                    $group = $di->session->get('usergroup');
                    $logingroup = $di->session->get('grouplogin');

                    ?>
                    <a href="#" data-target="#" class="dropdown-toggle"
                       data-toggle="dropdown"><?= $di->session->get('name') ?>
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="divider"></li>
                        <li><a href="javascript:void(0)"><?= $group[$logingroup] ?> <i class="md-done md-lg"></i></a>
                        </li>
                        <li class="divider"></li>
                        <?php
                        foreach ($group as $key => $val) {
                            if ($key <> $logingroup) {
                                echo '<li><a href="javascript:access_group(\'' . $key . '\',\'' . $val . '\')">' . $val . '</a></li>';
                            }
                        }
                        ?>


                    </ul>
                </li>
                <li><a href="javascript:logout()"><b>Logout</b></a></li>
            </ul>
        </div>
    </div>


<?php
} else {
    echo '<script>';
    echo 'alert("หมดเวลาการเข้าใช้งานระบบ (Session Time Out!!!");';
    echo 'window.location = "' . $di->url->get() . '"';
    echo '</script>';
}

?>





